[features]
seeds = false
skip-lint = false
[programs.localnet]
fng = "7TZeqvQd27xfZRFnjygaVJA3x6CbUn54qs55kxiZXycG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/chavers/solana/wallet/fng/fng4zZBNmue3xagL1CPGJsxrXWjrNRRatoMvo9ZXJKP.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
